# RT-Thread building script for component
import rtconfig
Import('RTT_ROOT')
from building import *

cwd = GetCurrentDir()
src = Split('''
Device/ST/STM32F3xx/Source/Templates/system_stm32f3xx.c
''')
CPPPATH = [cwd + '/Device/ST/STM32F3xx/Include', cwd + '/Include']

if GetDepend(['SOC_STM32F3xx']) or GetDepend(['SOC_STM32F334x8']) or GetDepend(['SOC_STM32F334C6']):
    STM32_TYPE = 'STM32F334x8'
    
CPPDEFINES = [STM32_TYPE]

# add for startup script 
if rtconfig.CROSS_TOOL == 'gcc':
     folder = 'gcc'
elif rtconfig.CROSS_TOOL == 'keil':
     folder = 'arm'
elif rtconfig.CROSS_TOOL == 'iar':
     folder = 'iar'
#Device/ST/STM32F3xx/Source/Templates/iar/startup_stm32f411xe.s     
src += ['Device/ST/STM32F3xx/Source/Templates/' + folder + '/startup_' + STM32_TYPE.lower() + '.s']

group = DefineGroup('CMSIS', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
